### PR TITLE
Adds forecasting weather function for just Bedford data. 

### PR DESCRIPTION
**Pull request by sk608**

### CODE REVIEW

**Comment by befriendabacterium** [comment]
Hey, this is impressive! Solid effort, Scarlett. 

A few bugs:

Line 1 - Function should be called relative2baseline.forecast.

Line 78 - Please go on OpenWeather and delete the API key you pushed to github and create a new one but don't put it in the code. Instead have an environmental variable/object called 'OWM_API_KEY' that you read from outside of the Github repo/file and on the local computer of the user.

Line 100 - you need to put a na.rm=T in there so that it sums up properly (you are just getting NA for rainfall values). Are those NAs 0s or true NAs? Can you find out? If they are true NAs and not 0s, I think it's better to do mean rainfall per hour instead.

**Comment by sk608** [comment]
Hey Matt,

Line 1- I thought the relative2baseline function works on both the forecasting data and the metoffice data so I thought we wanted to just call it relative 2 baseline?

Line 78 - Just so I understand it correctly. Would the object I create go to the OpenWeather site and extract your API key personally to the User?

Line 100- The NAs I believe are true NAs. It will be because for the whole of that day there is no predictor value and instead it's written as NA. I'll see if maybe when it comes up with NA if that does indeed mean no rainfall and I'm getting confused. Also it's already set to rainfall per hour.

**Comment by befriendabacterium** [comment]
Line 1 - When I ran it, this function only outputs the forecast data relative to baseline? 
Line 78 - Yes - we should keep API keys non-public as they are associated with a user account. So have to delete the one that's now public in the github repo history, generate a new one, and store it locally...will think about a long term solution to this...
Line 100 - ah, yes check on OpenWeather. If they're true NAs, mean is absolutely the way to go!

Call me if you want to chat this out on video call as might be easier

**Comment by sk608** [comment]
Yeah we can do! I'm just running the code to see if it does do the met office dataset!

**Comment by sk608** [comment]
Yeah, you're right. It should run both, I must have created a bug as I was altering the code!

**Comment by befriendabacterium** [comment]
outdated

**Pull request closed without merging**
